# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Abu Sabiq Mahdi
tagline:          'Portfolio Site'
description:      ''
url:              https://asmahdi.github.io
baseurl:          ''



plugins:             [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0


